
var Words = [ [ "abetted", "abiding", "ability", "abolish", "account", "actuate", "adamant" ],
	      [ "bumpkin", "bunting", "buoyant", "burette", "burgeon", "burglar" ],
	      [ "closing", "closure", "clothed", "clothes", "commute", "compact", "compare", "compass" ],
	      [ "deserve", "despair", "despise", "despite", "dessert", "dogfish", "doggone", "dogsled", "doleful", "dolphin", "donated", "doorman", "doormat", "dormant", "dossier", "doubled" ],
	      [ "eagerly", "eardrum", "earmark", "earmuff", "earnest", "earplug", "earring", "earshot", "earthen", "earthly", "embargo", "embroil", "emerald", "emirate", "example", "excited", "exclaim", "exclude", "excrete", "execute" ],
	      [ "ferrous", "fertile", "fervent", "fervour", "festive", "festoon" ],
	      [ "gambler", "garbage", "garbled", "grandad", "grandee", "grandpa", "granite", "granola", "granted", "granule", "graphic", "grapple", "grassed" ],
	      [ "habitat", "hacking", "hackles", "haddock", "haggard", "haggled", "heading", "healing" ],
	      [ "intoned", "intrude", "invader", "invalid", "inverse", "invited" ],
	      [ "jackass", "jackdaw", "jackpot", "janitor", "jasmine", "javelin", "jawbone", "jawline", "jaywalk", "jealous" ],
	      [ "killjoy", "kindred", "kinetic", "kingdom", "kingpin", "kinship", "kinsman" ],
	      [ "leather", "lectern", "lecture", "logging", "logical" ],
	      [ "message", "messiah", "methane", "microbe", "middled", "midriff", "midterm", "midtown" ],
	      [ "nagging", "natural", "naughty", "needled", "newborn", "nibbled", "nightie", "nightly", "nitrate" ],
	      [ "oarsman", "oatmeal", "obelisk", "obliged", "oblique", "obloquy", "overlap", "overlie", "origami", "oxydize" ],
	      [ "pacific", "package", "packing", "padding", "paddled", "paddock", "padlock", "piracy", "printer" ],
	      [ "quacked", "quantum", "quarter", "quartet", "quarrel", "quashed", "quintet", "quizzed" ],
	      [ "rigging", "rightly", "rimless", "ringlet", "riotous", "ripcord", "risible", "risotto", "rissole", "rotting", "rupture", "rustler" ], 
	      [ "sabbath", "sackful", "sacking", "sadness", "saffron", "sailing", "saintly", "schemer", "schlock", "scholar" ],
	      [ "tachyon", "tonight", "tonnage", "tonsure", "topiary", "topical", "topknot", "topping", "topsoil", "topspin", "torment", "tornado", "torpedo", "torrent", "torsion", "torture", "totally", "trailer", "trainee", "trainer", "traipse", "traitor", "trammel", "trample", "tranche", "transom" ],
	      [ "unnerve", "unquiet", "unquote", "unravel" ],
	      [ "vaccine", "vacuous", "vagrant", "valance", "valiant", "vampire", "version", "vestige", "veteran", "village" ],
	      [ "walkout", "walkway", "wallaby", "walling", "wanting", "warbler", "warfare", "warhead", "warlock", "warlord", "warming", "warning", "warpath", "warrant" ],
	      [ "yanking", "yardage", "yearned", "yielded", "yodeled", "younger" ],
	      [ "zealous", "zillion", "ziplock", "zoology" ]
];
